### ISSUE TITLE
Minor documentation issue

### ISSUE THREAD

**Issue by DaemonNFT** [drift-labs/protocol-v1#15]
The function on `src/math/funding.ts` all seem to reference `pythClient`, when the parameter in the signature is `oraclePriceData`. This is a little confusing - is the PythClient instance itself meant to be passed, of the result of `pythClient.getPriceData()`? See:

https://github.com/drift-labs/protocol-v1/blob/master/sdk/src/math/funding.ts#L15

**Comment by crispheaney** [comment]
Updated

https://github.com/drift-labs/protocol-v1/commit/3cc9d8837256bce1ec8c5f217d5d54f6518ccc4d
